Repository Evgeniya-star-35/EasyTicketsApp, pull requests merged in 2021-09, with the labels that each got.

#2 delete demo image
  src/images/demo.jpg
Labels: help wanted

#4 New branch images
  src/images/desctop/desctop-bg-body@1x.png
  src/images/desctop/desctop-bg-body@2x.png
  src/images/desctop/desctop-pic@1x.png
  src/images/desctop/desctop-pic@2x.png
  src/images/mobile/mobile-bg-body@1x.jpg
  src/images/mobile/mobile-pic@1x.png
  src/images/mobile/mobile-pic@2x.jpg
  src/images/mobile/mobole-bg-body@1x.png
  src/images/sprite.svg
  src/images/tablet/tablets-bg-body@1x.png
  src/images/tablet/tablets-bg-body@2x.jpg
  src/images/tablet/tablets-pic@1x.png
  src/images/tablet/tablets-pic@2x.png
  src/index.html
  src/sass/_header.scss
Labels: help wanted

#10 add icon
  src/images/sprite.svg
Labels: help wanted

#22 change-images
  src/images/desctop/bg-body@1x.jpg
  src/images/desctop/bg-body@2x.jpg
  src/images/desctop/desctop-bg-body@1x.png
  src/images/desctop/desctop-bg-body@2x.png
  src/images/desctop/desctop-pic@1x.png
  src/images/desctop/desctop-pic@2x.png
  src/images/desctop/pic@1x.jpg
  src/images/desctop/pic@2x.jpg
  src/images/mobile/mobile-pic@1x.jpg
  src/images/mobile/mobile-pic@1x.png
  src/images/mobile/mobile-pic@2x.jpg
  src/images/mobile/mobole-bg-body@1x.png
  src/images/mobile/mpbile-bg-body@2x.jpg
  src/images/tablet/tablets-bg-body@1x.jpg
  src/images/tablet/tablets-bg-body@1x.png
  src/images/tablet/tablets-bg-body@2x.jpg
  src/images/tablet/tablets-pic@1x.jpg
  src/images/tablet/tablets-pic@1x.png
  src/images/tablet/tablets-pic@2x.jpg
  src/images/tablet/tablets-pic@2x.png
Labels: help wanted

#23 changr path & pictures
  src/images/mobile/mobile-bg-body@2x.jpg
  src/sass/_gallery.scss
  src/sass/_header.scss
Labels: help wanted

#44 add render at onec
  src/index.js
  src/js/onload.js
Labels: good first issue

#45 add render on loaded at once
  src/index.js
  src/js/onload.js
Labels: help wanted

#49 add animation on gallery
  src/partials/gallery.html
  src/sass/_base.scss
  src/sass/_gallery.scss
  src/sass/utils/_variables.scss
Labels: help wanted

#50 add pagination
  src/index.js
  src/js/fetchEvents.js
  src/js/pagination.js
  src/js/refs.js
  src/partials/gallery.html
  src/sass/_pagination.scss
Labels: help wanted

#51 Не мержи без меня
  src/js/btnUp.js
Labels: bug

#54 fixBug
  src/js/btnUp.js
Labels: bug

#56 fixBug
  src/index.html
Labels: bug

#59 add country-code-link
  src/index.js
  src/js/country-code-link.js
  src/partials/header.html
  src/sass/_header.scss
  src/templates/selectMenu.hbs
Labels: help wanted

#61 pnotify+
  src/index.html
  src/index.js
  src/js/onload.js
Labels: help wanted

#68 Added logic to the page switcher
  src/index.js
  src/js/pagination.js
  src/js/refs.js
Labels: enhancement

#69 fix-mark
  src/js/onload.js
Labels: help wanted

#75 add PNotify
  src/index.js
  src/js/fetchSearch.js
  src/js/onload.js
  src/js/pnotify.js
  src/js/refs.js
  src/sass/_base.scss
Labels: help wanted

#82 fix-price
  src/templates/galleryModalCard.hbs
Labels: help wanted

#93 +++
  src/index.js
  src/js/fetchEvents.js
  src/js/modal.js
  src/js/moreButton.js
  src/templates/galleryModalCard.hbs
Labels: bug

#96 newFix+moreButton
  src/index.js
  src/js/fetchSearch.js
  src/js/modal.js
  src/js/moreButton.js
  src/js/renderFirstWord.js
Labels: help wanted

#97 connect in index.js clickByLogo
  src/index.js
Labels: oooops 🤭

#101 change default word +
  src/js/onload.js
Labels: oooops 🤭
